### ISSUE TITLE
Unintuitive names

### ISSUE THREAD

**Issue by Huy-Ngo** [dinhanhx/Morphology_Study#1]
We have several functions or variables with unintuitive names in very-simple-morphological.py (the filename itself is also unintuitive) which give little idea of what they do.

Here are the ones I think should be renamed:

- `strel`
- `baw_img`
- `morph()`
- `nbh_row`, `nbh_row_ful`, `nbh_col`, `nbh_col_ful`
- strings: `"ero"`, `"dil"`

By the way, `type` is a builtin function in python, so even though we maybe won't use it, it's best to avoid overwriting that function.

**Comment by dinhanhx** [comment]
Here are the list I can think of:
- `strel` to `structure_element`
- `baw_img` to `black_white_img`
- `nbh_` to `neighbor`
- `ero` to `erosion` and `dil` to `dilation`
- `type` to `technique`/`mode`/`operation`

For changing the name of the function `morp()`, I propose that we should call it `get_morpheme()`.

**Comment by dinhanhx** [comment]
For the name of the file, in stead of calling `very-simple-morphological.py`, we should change it to `morphological_methods.py`

**Comment by huonglarne** [comment]
fixed all, except type argument. i think erosion, dilation and stuff are types of morphological processing. technique is the morphology itself, using structure element and hit/miss. Picture to prove my point.

![image](https://user-images.githubusercontent.com/59214421/84804682-5720b680-b02d-11ea-9770-895c3f7a3311.png)

**Comment by Huy-Ngo** [comment]
Close via fcf3c99
