### ISSUE TITLE
Try different morphology algorithms for image sets

### ISSUE THREAD

**Issue by dinhanhx** [dinhanhx/Morphology_Study#2]
All of the following morphological transformations are already implemented in [`cv2.morphologyEx()`](https://docs.opencv.org/2.4/modules/imgproc/doc/filtering.html?highlight=morphologyex#morphologyex)

Basic algorithms:
- [x] Opening: erosion then dilation
- [x] Closing: dilation then erosion
- [x] Gradient: the difference between the dilation and erosion

Intermediate algorithms:
- [x] White top-hat: the difference between Opening and original image
- [x] Black top-hat: the difference between Closing and original image
- [x] Hit and miss

Please try each algorithm with various parameters and record the results for report. Please also explain the algorithms in the report as well.

Each of these would have its own issue for tracking. Please only check the above when you're done with your task.

**Comment by dinhanhx** [comment]
There are 2 functions in opencv which are `cv2.dilate()` and `cv2.erode`. Therefore, this should be carried out easily. There is `cv2.morphologyEx()`

**Comment by huonglarne** [comment]
done all. please check code.

**Comment by Huy-Ngo** [comment]
I'm not sure whether @dinhanhx means we should resolve this by implementing these from scratch or write code with OpenCV and run on the sample images.

**Comment by dinhanhx** [comment]
According basic requirements of topic, we should use opencv. Here is just the list to track methods. We can resolve this issue by both ways in the same time.

**Comment by Huy-Ngo** [comment]
Let's hope we get these done before the next Thursday 2020-06-25

**Comment by dinhanhx** [comment]
Rename issue. ~both~ CAPTCHA

**Comment by dinhanhx** [comment]
Due to the lack of time, I will handle this. Deadline to close Tmr.
