### ISSUE TITLE
Try opening and closing operation

### ISSUE THREAD

**Issue by Huy-Ngo** [dinhanhx/Morphology_Study#4]
Please run `morphologyEx()` with `MORPH_OPEN` and `MORPH_CLOSE` with varying parameters and record the results.

**Comment by Huy-Ngo** [comment]
Gentle ping @huonglarne

**Comment by dinhanhx** [comment]
@huonglarne If you are busy with self-impl, I will take over this issue for you.

**Comment by dinhanhx** [comment]
Due to the lack of time, I will handle this. Deadline to close Tmr.
