### ISSUE TITLE
Try gradient morphology operation on the images

### ISSUE THREAD

**Issue by Huy-Ngo** [dinhanhx/Morphology_Study#5]
Please run `morphologyEx()` with `MORPH_GRADIENT` with varying parameters and record the results.

**Comment by Huy-Ngo** [comment]
Gentle ping @DDHLong

**Comment by Huy-Ngo** [comment]
Are you still there @DDHLong

**Comment by dinhanhx** [comment]
@DDHLong is now in his country home. He said he will be back to his home on Sunday 28/6/2020.

**Comment by dinhanhx** [comment]
Due to the lack of time, I will handle this. Deadline to close Tmr.
