### ISSUE TITLE
Try top hat algorithms on the images

### ISSUE THREAD

**Issue by Huy-Ngo** [dinhanhx/Morphology_Study#6]
Please run `morphologyEx()` with `MORPH_TOPHAT` and `MORPH_BLACKHAT` with varying parameters and record the results as well as explanation of why and algorithms.

**Comment by dinhanhx** [comment]
## A note for myself

- `cv2.MORPH_TOPHAT` refers to top hat/ white hat
- `cv2.MORPH_BLACKHAT` refers to bottom hat/ black hat

File name pattern:
- `tophat_blackhat.py`

[opencv morphologyEx()](https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_imgproc/py_morphological_ops/py_morphological_ops.html)
